version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=rssgo
      - CGO_ENABLED=1
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
  app:
    build: .
    ports:
      - 8080:8000
    environment:
      - CGO_ENABLED=1
    volumes:
      - ./.env:/app/.env
      - ./sql:/app/sql